"""switch geom to geog.

Revision ID: 06f358d1aec7
Revises: 2c32db53b20c
Create Date: 2023-09-02 12:16:08.160676
"""
from typing import Sequence, Union

import geoalchemy2
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '06f358d1aec7'
down_revision: Union[str, None] = '2c32db53b20c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Adjusted
    op.alter_column(
        'photos',
        'location',
        existing_type=geoalchemy2.types.Geometry(
            geometry_type='POINT',
            from_text='ST_GeomFromEWKT',
            name='geometry',
            nullable=False,
            _spatial_index_reflected=True,
        ),
        type_=geoalchemy2.types.Geography(
            geometry_type='POINT',
            srid=4326,
            from_text='ST_GeogFromText',
            name='geography',
            nullable=False,
        ),
        existing_nullable=False,
    )
    op.create_foreign_key(
        op.f('users_language_code_fkey'),
        'users',
        'languages',
        ['language_code'],
        ['code'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Adjusted
    op.drop_constraint(
        op.f('users_language_code_fkey'),
        'users',
        type_='foreignkey',
    )
    op.alter_column(
        'photos',
        'location',
        existing_type=geoalchemy2.types.Geography(
            geometry_type='POINT',
            srid=4326,
            from_text='ST_GeogFromText',
            name='geography',
            nullable=False,
        ),
        type_=geoalchemy2.types.Geometry(
            geometry_type='POINT',
            from_text='ST_GeomFromEWKT',
            name='geometry',
            nullable=False,
            _spatial_index_reflected=True,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
