"""Initial.

Revision ID: 0a4cdbb19b27
Revises:
Create Date: 2023-08-31 10:23:39.921721
"""
from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0a4cdbb19b27'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Commands adjusted
    op.execute('CREATE EXTENSION postgis;')

    op.create_table(
        'hashtags',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('hashtag', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk__hashtags')),
        sa.UniqueConstraint('hashtag', name=op.f('uq__hashtags__hashtag')),
    )

    op.create_table(
        'languages',
        sa.Column('code', sa.String(length=2), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('code', name=op.f('pk__languages')),
    )

    op.create_table(
        'users',
        sa.Column(
            'telegram_id',
            sa.BigInteger(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column('language_code', sa.String(length=2), nullable=False),
        sa.Column(
            'is_active',
            sa.Boolean(),
            server_default='true',
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('telegram_id', name=op.f('pk__users')),
    )

    op.create_table(
        'photos',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('preview', sa.String(), nullable=False),
        sa.Column(
            'location',
            geoalchemy2.types.Geometry(
                geometry_type='POINT',
                from_text='ST_GeomFromEWKT',
                name='geometry',
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.telegram_id'],
            name=op.f('photos_user_id_fkey'),
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk__photos')),
    )

    op.create_table(
        'photos_hashtags',
        sa.Column('photo_id', sa.String(), nullable=False),
        sa.Column('hashtag_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['hashtag_id'],
            ['hashtags.id'],
            name=op.f('photos_hashtags_hashtag_id_fkey'),
        ),
        sa.ForeignKeyConstraint(
            ['photo_id'],
            ['photos.id'],
            name=op.f('photos_hashtags_photo_id_fkey'),
        ),
        sa.PrimaryKeyConstraint(
            'photo_id',
            'hashtag_id',
            name=op.f('pk__photos_hashtags'),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Commands adjusted
    op.drop_table('photos_hashtags')
    op.drop_table('photos')
    op.drop_table('users')
    op.drop_table('languages')
    op.drop_table('hashtags')
    # ### end Alembic commands ###
