"""Add photo description.

Revision ID: 2c32db53b20c
Revises: 0a4cdbb19b27
Create Date: 2023-08-31 11:08:19.092345
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2c32db53b20c'
down_revision: Union[str, None] = '0a4cdbb19b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Adjusted
    op.add_column('photos', sa.Column('description', sa.String()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Adjusted
    op.drop_column('photos', 'description')
    # ### end Alembic commands ###
