"""Split id and file_id

Revision ID: 3e9003225d01
Revises: 36814d16f264
Create Date: 2023-09-10 01:43:04.258945
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3e9003225d01'
down_revision: Union[str, None] = '36814d16f264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Adjusted
    op.drop_constraint('photos_hashtags_photo_id_fkey', 'photos_hashtags')
    op.alter_column('photos', 'id', new_column_name='file_id')
    op.alter_column(
        'photos_hashtags',
        'photo_id',
        type_=sa.Integer,
        postgresql_using='photo_id::integer',
    )
    op.add_column(
        'photos',
        sa.Column(
            'id', sa.Integer, primary_key=True, unique=True, autoincrement=True,
        ),
    )
    op.create_foreign_key(
        'photos_hashtags_photo_id_fkey',
        'photos_hashtags',
        'photos',
        ['photo_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Adjusted
    op.drop_constraint('photos_hashtags_photo_id_fkey', 'photos_hashtags')
    op.drop_column('photos', 'id')
    op.alter_column('photos', 'file_id', new_column_name='id')
    op.alter_column(
        'photos_hashtags',
        'photo_id',
        type_=sa.String,
    )
    op.create_foreign_key(
        'photos_hashtags_photo_id_fkey',
        'photos_hashtags',
        'photos',
        ['photo_id'],
        ['id'],
    )

    # ### end Alembic commands ###
