"""Remove preview.

Revision ID: 973f798e8331
Revises: e3eefd8da820
Create Date: 2023-09-02 23:00:52.848034
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '973f798e8331'
down_revision: Union[str, None] = 'e3eefd8da820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Adjusted
    op.drop_column('photos', 'preview')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Adjusted
    op.add_column(
        'photos',
        sa.Column(
            'preview',
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
